---
title: "Time Series"
navbar:
    left:
      
      - about.qmd
      - Introduction.qmd
      - DataSources.qmd
      - DataVis.qmd
      - EDA.qmd
      - ARModels.qmd
      - ASV.qmd

      - GARCH.qmd
      - TS.qmd
      - conclusion.qmd
      - dv.qmd

format:
  html:
    theme: sandstone 
    css: ./styles/layout.css
    toc: true
---



# Time Series: ANLY-5600
Author: Zonghong Yu

NetID: zy236

Email: zy236@georgetown.edu

# Zonghong Yu's Background


Zonghong Yu is an international student from Shanghai, China. He came into the DSAN program at Georgetown University. For his undergraduate experience, he studied at Rensselaer Polytechnic Institute. His managed to complete a dual-major: Computer and System Engineering & Industrial and System Engineering. His minor was Data Science. The reason for choosing these majors was that he wanted to learn as much as he can to experience different fields so that he could find his interests and strength to search opportunities in the future studies. While learning, he also managed to get a few internship experience. He worked as a Quantitative Analyst Intern during the third year in college. And He worked as a Data Analyst Intern during the fourth year before graduating. Which provided useful experiences for preparing the graduate degree in Georgetown. After graduating, the ideal professional career would be Data Scientist, taking the role to analyze diverse and challenging datasets to understand and implement models to help solve problems in our real life. However, before that, he needs to enrich himself with more different experiences and knowledge in Georgetown and prepare to overcome the challenges in different subjects such as big data and cloud computing, algorithms, and deep learning. As for his hobbies, he loves playing badminton in any free time. In addition, He is always excited to watch movies and play games with others when feeling stressed. He also wish to develop new hobbies during time in Georgetown by meeting new friends and learning from professors.

# Academic Interests

## Major Subjects that Zonghong interests in or wants to explore:

- Python, RStudio

- Data Science, Math, Time Series, Programming

- Finance, Quantitative Engineering

- Data Visulization

# Education
2022 - 2024: MS in Georgetown University

2018 - 2022: Bachelor's in Rensselaer Polytechnic Institute

2015 - 2018: Songjiang No. 2 Middle School, Shanghai, China

